### PR TITLE
DOC: Add a note about .pyproj vs .vcxproj

### PR DESCRIPTION
**Pull request by dzenanz**

### CODE REVIEW

**Comment by lassoan** [comment]
I'm not sure if the project type actually matters. Maybe the default code type is set to Python script if you use .pyproj. What is actually important is to select the correct code type for "Attach to":

image

**Comment by dzenanz** [comment]
I tried all the options there, it did not help.

**Comment by lassoan** [comment]
OK, let's update the documentation then.

**Comment by lassoan** [comment]
Thank you @dzenanz for taking the time to help others.

**Pull request merged**
